export const slides = [
  {
    id: 0,
    title: 'PCs',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    description: "USE ITI-PCs PROMO CODE AND GET DISCOUNT 30%",
    img_url: "https://www.pngarts.com/files/4/HP-Laptop-PNG-Image.png",
    bg: "#dbe0ca"
  },
  {
    id: 1,
    title: 'Phones & Tablets',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    description: "BEST MODERN PHONES WITH THE BEST PRICE SHOP NOW!",
    img_url: "https://www.pngarts.com/files/18/iPhone-14-Pro-Download-PNG-Image.png",
    bg: "lightblue"
  },
  {
    id: 2,
    title: 'Acessories',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    description: "TRADE IN TRADE YOUR OLD ACSSEORIES WITH NEW ONE",
    img_url: "https://www.pngarts.com/files/8/Wireless-Earphone-Transparent-Image.png",
    bg: "#fbf0f4"
  },
]


export const categories = [
  {
    id: 0,
    title: 'Pcs & Labtops!',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img_url: "https://i.pinimg.com/236x/b4/3c/0b/b43c0b0d65e7500b6f95222ae5021835.jpg",
    cat: 'Pcs'
  },
  {
    id: 1,
    title: 'Phones',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img_url: "https://i.pinimg.com/236x/05/01/a1/0501a12a3eb02684a7672f555f899ee9.jpg",
    cat: 'Phones'
  },
  {
    id: 2,
    title: 'Gadgets!',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img_url: "https://i.pinimg.com/236x/c4/3d/47/c43d4770e7497ce2e7481f24a22a9fbe.jpg",
    cat: 'Gadgets'
  },
]

export const popularProducts = [
  {
    id: 1,
    title:"Mega PC",
    img: "https://www.pngarts.com/files/2/Personal-Computer-PNG-Picture.png",
    cat: 'Pcs',
    size: ['xs', 'm', 'l'],
    color: ['red', 'black', 'white', 'orange'],
    stock: 25,
    price: 10,
  },
  {
    id: 2,
    title: 'Personal Computer X',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/2/Personal-Computer-PNG-Image-Transparent.png",
    cat: 'pcs',
    size: ['l', 'xl'],
    color: ['indianred', 'black',],
    stock: 14,
    price: 8,
  },
  {
    id: 8,
    title: 'Air Bods',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/8/Airpod-Transparent-Background-PNG.png",
    cat: 'gadgets',
    size: ['s', 'm'],
    color: ['white', 'sandybrown'],
    stock: 12,
    price: 80,
  },
  {
    id: 9,
    title: 'Acer',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/4/Phone-Transparent-Background-PNG.png",
    cat: 'phones',
    size: ['xs', 's', 'm'],
    color: ['black', 'white'],
    stock: 18,
    price: 35,
  },
  {
    id: 10,
    title: 'IPhone 14',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/18/iPhone-14-Pro-PNG-Download-Image.png",
    cat: 'phones',
    size: ['m', 'xl'],
    color: ['black', 'white', 'gray'],
    stock: 7,
    price: 30,
  },
  {
    id: 11,
    title: 'RTX Compuetr',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/2/Personal-Computer-Download-Transparent-PNG-Image.png",
    cat: 'pcs',
    size: ['xs'],
    color: ['orangered', 'black', 'white'],
    stock: 12,
    price: 20,
  },
  {
    id: 12,
    title: 'Antique Computer',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/2/Personal-Computer-Free-PNG-Image.png",
    cat: 'pcs',
    size: ['xs', 's', 'm', 'l'],
    color: ['white', 'yellow'],
    stock: 21,
    price: 25,
  },
  {
    id: 13,
    title: 'Mac',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/Mac-Transparent-Images.png",
    cat: 'pcs',
    size: ['s', 'm', 'l'],
    color: ['black', 'white',],
    stock: 9,
    price: 15,
  },
  {
    id: 14,
    title: 'Alexa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/8/Alexa-Echo-PNG-Image-Background.png",
    cat: 'gadgets',
    size: ['xs', 'l'],
    color: ['darkorange'],
    stock: 37,
    price: 120,
  },
  {
    id: 15,
    title: 'Apple Watch',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/8/Black-Apple-Watch-Series-5-PNG-Image-Background.png",
    cat: 'gadgets',
    size: ['xs', 'm',],
    color: ['black', 'white', 'orange'],
    stock: 14,
    price: 140,
  },
  {
    id: 16,
    title: 'Smart Watch',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/8/Black-Apple-Watch-Series-6-Download-Image.png",
    cat: 'gadgets',
    size: ['m', 'l', 'xl'],
    color: ['white', 'lightblue'],
    stock: 41,
    price: 220,
  },
  {
    id: 17,
    title: 'Power Bank',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/9/Smartphone-Power-Bank-PNG-Image-Transparent-Background.png",
    cat: 'gadgets',
    size: ['xs', 's', 'l'],
    color: ['white', 'lightblue'],
    stock: 27,
    price: 150,
  },
  {
    id: 18,
    title: 'Head Phone',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/9/Wireless-Headphones-PNG-Background-Image.png",
    cat: 'gadgets',
    size: ['m', 'l', 'xl'],
    color: ['rosybrown', 'black'],
    stock: 17,
    price: 100,

  },
  {
    id: 19,
    title: 'Gaming Keyboard',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/4/Gaming-Keyboard-PNG-Pic.png",
    cat: 'gadgets',
    size: ['xs', 's', 'm', 'xl'],
    color: ['black', 'deeppink'],
    stock: 10,
    price: 140,
  },
  {
    id: 20,
    title: 'PC mouse',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/4/PC-Mouse-PNG-Pic.png",
    cat: 'gadgets',
    size: ['s', 'm', 'l'],
    color: ['black',],
    stock: 19,
    price: 200,
  },
  {
    id: 21,
    title: 'Type C',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/9/Type-C-Charger-Adapter-PNG-Image-Background.png",
    cat: 'gadgets',
    size: ['xs', 's', 'm'],
    color: ['black', 'brown'],
    stock: 11,
    price: 350,
  },
  {
    id: 22,
    title: 'Flash Disk',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/3/Pen-Drive-Transparent-Background-PNG.png",
    cat: 'gadgets',
    size: ['s', 'm', 'l',],
    color: ['black'],
    stock: 58,
    price: 275,
  },
  {
    id: 23,
    title: 'IPad',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/18/iPad-Mockup-PNG.png",
    cat: 'phones',
    size: ['s', 'm'],
    color: ['black'],
    stock: 13,
    price: 90,
  },
  {
    id: 24,
    title: 'Mac labtop',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/Mac-Laptop-PNG-Transparent-Image.png",
    cat: 'pcs',
    size: ['s', 'l'],
    color: ['white', 'orange'],
    stock: 25,
    price: 50,
  },
  {
    id: 25,
    title: 'MacBook',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/Macbook-PNG-Pic.png",
    cat: 'pcs',
    size: ['xs', 's', 'm', 'l', 'xl'],
    color: ['black'],
    stock: 25,
    price: 35,
  },
 

]


const test = async () => {
  const popularProducts = [
    {
      title: 'Personal Computer X',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/2/Personal-Computer-PNG-Image-Transparent.png",
      category: 'pcs',
      size: ['xs', 'm', 'l'],
      color: ['red', 'black', 'white', 'orange'],
      stock: 25,
      price: 10,
    },
    {
      title: 'RTX Compuetr',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/2/Personal-Computer-Download-Transparent-PNG-Image.png",
      category: 'pcs',
      size: ['l', 'xl'],
      color: ['indianred', 'black',],
      stock: 14,
      price: 8,
    },
    {
      title: 'Air Bods',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/8/Airpod-Transparent-Background-PNG.png",
      category: 'gadgets',
      size: ['s', 'm'],
      color: ['white', 'sandybrown'],
      stock: 12,
      price: 80,
    },
    {
      title: 'Acer',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/4/Phone-Transparent-Background-PNG.png",
      category: 'phones',
      size: ['xs', 's', 'm'],
      color: ['black', 'white'],
      stock: 18,
      price: 35,
    },
    {
      title: 'Iphone 14',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/18/iPhone-14-Pro-PNG-Download-Image.png",
      category: 'phones',
      size: ['m', 'xl'],
      color: ['black', 'white', 'gray'],
      stock: 7,
      price: 30,
    },
    {
      title: 'Antique Computer',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/2/Personal-Computer-Free-PNG-Image.png",
      category: 'pcs',
      size: ['xs'],
      color: ['orangered', 'black', 'white'],
      stock: 12,
      price: 20,
    },
    {
      title: 'Mac',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Mac-Transparent-Images.png",
      category: 'pcs',
      size: ['xs', 's', 'm', 'l'],
      color: ['white', 'yellow'],
      stock: 21,
      price: 25,
    },
    {
      title: 'Mac labtop',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Mac-Laptop-PNG-Transparent-Image.png",
      category: 'pcs',
      size: ['s', 'm', 'l'],
      color: ['black', 'white',],
      stock: 9,
      price: 15,
    },
    {
      title: 'Alexa',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/8/Alexa-Echo-PNG-Image-Background.png",
      category: 'gadgets',
      size: ['xs', 'l'],
      color: ['darkorange'],
      stock: 37,
      price: 120,
    },
    {
      title: 'Apple Watch',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/8/Black-Apple-Watch-Series-5-PNG-Image-Background.png",
      category: 'gadgets',
      size: ['xs', 'm',],
      color: ['black', 'white', 'orange'],
      stock: 14,
      price: 140,
    },
    {
      title: 'Smart Watch',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/8/Black-Apple-Watch-Series-6-Download-Image.png",
      category: 'gadgets',
      size: ['m', 'l', 'xl'],
      color: ['white', 'lightblue'],
      stock: 41,
      price: 220,
    },
    {
      title: 'Power Bank',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/9/Smartphone-Power-Bank-PNG-Image-Transparent-Background.png",
      category: 'gadgets',
      size: ['xs', 's', 'l'],
      color: ['white', 'lightblue'],
      stock: 27,
      price: 150,
    },
    {
      title: 'Head Phone',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/9/Wireless-Headphones-PNG-Background-Image.png",
      category: 'gadgets',
      size: ['m', 'l', 'xl'],
      color: ['rosybrown', 'black'],
      stock: 17,
      price: 100,

    },
    {
      title: 'Gaming Keyboard',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/4/Gaming-Keyboard-PNG-Pic.png",
      category: 'gadgets',
      size: ['xs', 's', 'm', 'xl'],
      color: ['black', 'deeppink'],
      stock: 10,
      price: 140,
    },
    {
      title: 'PC mouse',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/4/PC-Mouse-PNG-Pic.png",
      category: 'gadgets',
      size: ['s', 'm', 'l'],
      color: ['black',],
      stock: 19,
      price: 200,
    },
    {
      title: 'Type C',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/9/Type-C-Charger-Adapter-PNG-Image-Background.png",
      category: 'gadgets',
      size: ['xs', 's', 'm'],
      color: ['black', 'brown'],
      stock: 11,
      price: 350,
    },
    {
      title: 'Flash Disk',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/3/Pen-Drive-Transparent-Background-PNG.png",
      category: 'gadgets',
      size: ['s', 'm', 'l',],
      color: ['black'],
      stock: 58,
      price: 275,
    },
    {
      title: 'IPad',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/18/iPad-Mockup-PNG.png",
      category: 'phones',
      size: ['s', 'm'],
      color: ['black'],
      stock: 13,
      price: 90,
    },
    {
      title: 'MacBook',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Macbook-PNG-Pic.png",
      category: 'pcs',
      size: ['s', 'l'],
      color: ['white', 'orange'],
      stock: 25,
      price: 50,
    },
    {
      title: 'Pc',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Macbook-PNG-Pic.png",
      category: 'pcs',
      size: ['xs', 's', 'm', 'l', 'xl'],
      color: ['black'],
      stock: 25,
      price: 35,
    },
    
  ]
  for (const product of popularProducts) {
    const req = await fetch('http://127.0.0.1:1921/api/v1/product', {
      method: 'POST',
      headers: {
        "Content-type": "application/json"
      },
      body: JSON.stringify(product)
    })
    console.log(req)
  }
}